# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/cloudfoundry/gosigar"
  version = "1.1.0"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "18.0.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-syslog"

[[constraint]]
  branch = "master"
  name = "github.com/lukesampson/figlet"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/arsham/rainbow"
  version = "0.1.0"
